
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package panda.Parse;

import panda.Absyn.*;
import javaslang.collection.List;
import panda.ErrorMsg.Loc;
import panda.ErrorMsg.ErrorMsg;
import panda.Symbol.Symbol;
import java_cup.runtime.SymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141204 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class PandaCup extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return PandaSym.class;
}

  /** Default constructor. */
  public PandaCup() {super();}

  /** Constructor which sets the default scanner. */
  public PandaCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public PandaCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\020\000\002\002\004\000\002\002\003\000\002\004" +
    "\003\000\002\003\003\000\002\003\003\000\002\003\003" +
    "\000\002\003\010\000\002\003\006\000\002\003\003\000" +
    "\002\003\006\000\002\003\006\000\002\003\003\000\002" +
    "\005\010\000\002\005\006\000\002\006\003\000\002\006" +
    "\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\042\000\022\004\005\005\011\006\013\007\012\012" +
    "\016\013\006\014\004\032\014\001\002\000\022\004\005" +
    "\005\011\006\013\007\012\012\016\013\006\014\004\032" +
    "\014\001\002\000\016\002\ufffd\010\ufffd\011\ufffd\015\ufffd" +
    "\027\ufffd\033\ufffd\001\002\000\016\002\ufff9\010\ufff9\011" +
    "\ufff9\015\ufff9\027\ufff9\033\ufff9\001\002\000\004\002\000" +
    "\001\002\000\004\002\041\001\002\000\016\002\ufffc\010" +
    "\ufffc\011\ufffc\015\ufffc\027\ufffc\033\ufffc\001\002\000\022" +
    "\004\005\005\011\006\013\007\012\012\016\013\006\014" +
    "\004\032\014\001\002\000\016\002\uffff\010\uffff\011\uffff" +
    "\015\uffff\027\uffff\033\uffff\001\002\000\004\027\017\001" +
    "\002\000\016\002\ufff6\010\ufff6\011\ufff6\015\ufff6\027\ufff6" +
    "\033\ufff6\001\002\000\016\002\ufffe\010\ufffe\011\ufffe\015" +
    "\ufffe\027\ufffe\033\ufffe\001\002\000\004\006\025\001\002" +
    "\000\004\033\023\001\002\000\006\027\017\033\ufff3\001" +
    "\002\000\004\033\ufff2\001\002\000\022\004\005\005\011" +
    "\006\013\007\012\012\016\013\006\014\004\032\014\001" +
    "\002\000\016\002\ufff7\010\ufff7\011\ufff7\015\ufff7\027\ufff7" +
    "\033\ufff7\001\002\000\006\031\027\035\026\001\002\000" +
    "\022\004\005\005\011\006\013\007\012\012\016\013\006" +
    "\014\004\032\014\001\002\000\004\006\030\001\002\000" +
    "\004\035\031\001\002\000\022\004\005\005\011\006\013" +
    "\007\012\012\016\013\006\014\004\032\014\001\002\000" +
    "\006\027\ufff5\033\ufff5\001\002\000\006\027\ufff4\033\ufff4" +
    "\001\002\000\004\010\035\001\002\000\022\004\005\005" +
    "\011\006\013\007\012\012\016\013\006\014\004\032\014" +
    "\001\002\000\016\002\ufffa\010\ufffa\011\037\015\ufffa\027" +
    "\ufffa\033\ufffa\001\002\000\022\004\005\005\011\006\013" +
    "\007\012\012\016\013\006\014\004\032\014\001\002\000" +
    "\016\002\ufffb\010\ufffb\011\ufffb\015\ufffb\027\ufffb\033\ufffb" +
    "\001\002\000\004\002\001\001\002\000\004\015\043\001" +
    "\002\000\022\004\005\005\011\006\013\007\012\012\016" +
    "\013\006\014\004\032\014\001\002\000\016\002\ufff8\010" +
    "\ufff8\011\ufff8\015\ufff8\027\ufff8\033\ufff8\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\042\000\010\002\007\003\006\004\014\001\001\000" +
    "\006\003\041\004\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\003\033\004\014\001\001\000\002\001\001" +
    "\000\006\005\020\006\017\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\005\020\006\021\001\001\000\002\001\001\000\006\003" +
    "\023\004\014\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\003\032\004\014\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\003\031\004\014\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\003" +
    "\035\004\014\001\001\000\002\001\001\000\006\003\037" +
    "\004\014\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\003\043\004\014\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$PandaCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$PandaCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$PandaCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


//@@CUPDBG1

  ErrorMsg errorMsg;
  
  public PandaCup(PandaLex lex, SymbolFactory symbolFactory, ErrorMsg errorMsg) {
    this(lex, symbolFactory);
    this.errorMsg = errorMsg;
  }


  Loc loc(Location left, Location right) {
    return new Loc(left, right);
  }
 
  public void report_error(String message, Object info) {
    Loc loc;
    if (info instanceof ComplexSymbol) {
      ComplexSymbol tok = (ComplexSymbol) info;
      loc = loc(tok.xleft, tok.xright);
      message += ": " + Tokens.dumpToken(tok);
    }
    else
      loc = new Loc();
    errorMsg.error(loc, message);
  }

  public void syntax_error(java_cup.runtime.Symbol tok) {
    report_error("syntax error", tok);
  }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$PandaCup$actions {

//@@CUPDBG0

  //static Loc loc() 

  //{
  //  return new Loc();
  //}

  Loc loc(Location left, Location right) {
    return parser.loc(left, right);
  }

  private final PandaCup parser;

  /** Constructor */
  CUP$PandaCup$actions(PandaCup parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$PandaCup$do_action_part00000000(
    int                        CUP$PandaCup$act_num,
    java_cup.runtime.lr_parser CUP$PandaCup$parser,
    java.util.Stack            CUP$PandaCup$stack,
    int                        CUP$PandaCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$PandaCup$result;

      /* select the action based on the action number */
      switch (CUP$PandaCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		Location start_valxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-1)).xleft;
		Location start_valxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-1)).xright;
		Exp start_val = (Exp)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-1)).value;
		RESULT = start_val;
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-1)), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$PandaCup$parser.done_parsing();
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= exp 
            {
              Exp RESULT =null;
		Location xxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location xxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Exp x = (Exp)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG2
 RESULT = x; 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // var ::= ID 
            {
              Var RESULT =null;
		Location vxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location vxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Symbol v = (Symbol)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG3
 RESULT = new SimpleVar(loc(vxleft,vxright),v); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("var",2, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // exp ::= LITREAL 
            {
              Exp RESULT =null;
		Location xxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location xxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Double x = (Double)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG4
 RESULT = new RealExp(loc(xxleft,xxright),x); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("exp",1, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // exp ::= LITINT 
            {
              Exp RESULT =null;
		Location xxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location xxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Long x = (Long)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG5
 RESULT = new IntExp(loc(xxleft,xxright),x); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("exp",1, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // exp ::= LITBOOL 
            {
              Exp RESULT =null;
		Location xxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location xxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Boolean x = (Boolean)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG6
 RESULT = new BoolExp(loc(xxleft,xxright),x); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("exp",1, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // exp ::= IF exp THEN exp ELSE exp 
            {
              Exp RESULT =null;
		Location ixleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-5)).xleft;
		Location ixright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-5)).xright;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-5)).value;
		Location txleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-4)).xleft;
		Location txright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-4)).xright;
		Exp t = (Exp)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-4)).value;
		Location axleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).xleft;
		Location axright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).xright;
		Exp a = (Exp)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).value;
		Location bxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location bxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Exp b = (Exp)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG7
 RESULT = new IfExp(loc(ixleft,bxright),t,a,b); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("exp",1, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-5)), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // exp ::= IF exp THEN exp 
            {
              Exp RESULT =null;
		Location ixleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)).xleft;
		Location ixright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)).xright;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)).value;
		Location txleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).xleft;
		Location txright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).xright;
		Exp t = (Exp)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).value;
		Location axleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location axright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Exp a = (Exp)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG8
 RESULT = new IfExp(loc(ixleft,axright),t,a,null); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("exp",1, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // exp ::= LITCHAR 
            {
              Exp RESULT =null;
		Location xxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location xxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Character x = (Character)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG9
 RESULT = new CharExp(loc(xxleft,xxright),x); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("exp",1, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // exp ::= WHILE exp DO exp 
            {
              Exp RESULT =null;
		Location testxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).xleft;
		Location testxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).xright;
		Exp test = (Exp)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).value;
		Location resultxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location resultxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Exp result = (Exp)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG10
 RESULT = new WhileExp(loc(testxleft,resultxright),test,result); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("exp",1, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // exp ::= LET decs IN exp 
            {
              Exp RESULT =null;
		Location lxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)).xleft;
		Location lxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)).xright;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)).value;
		Location dxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).xleft;
		Location dxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).xright;
		List<Dec> d = (List<Dec>)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).value;
		Location xxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location xxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Exp x = (Exp)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG11
 RESULT = new LetExp(loc(lxleft,xxright),d,x); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("exp",1, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // exp ::= var 
            {
              Exp RESULT =null;
		Location vxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location vxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Var v = (Var)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG12
 RESULT = new VarExp(loc(vxleft,vxright),v); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("exp",1, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // dec ::= VAR ID COLON ID EQ exp 
            {
              Dec RESULT =null;
		Location vxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-5)).xleft;
		Location vxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-5)).xright;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-5)).value;
		Location nxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-4)).xleft;
		Location nxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-4)).xright;
		Symbol n = (Symbol)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-4)).value;
		Location txleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).xleft;
		Location txright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).xright;
		Symbol t = (Symbol)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).value;
		Location exleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location exright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG13
 RESULT = new VarDec(loc(vxleft,exright), n, t ,e); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("dec",3, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-5)), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // dec ::= VAR ID EQ exp 
            {
              Dec RESULT =null;
		Location vxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)).xleft;
		Location vxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)).xright;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)).value;
		Location nxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).xleft;
		Location nxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).xright;
		Symbol n = (Symbol)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-2)).value;
		Location exleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location exright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG14
 RESULT = new VarDec(loc(vxleft,exright), n, null ,e); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("dec",3, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-3)), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // decs ::= dec 
            {
              List<Dec> RESULT =null;
		Location dxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location dxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		Dec d = (Dec)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG15
 RESULT = List.of(d); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("decs",4, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // decs ::= dec decs 
            {
              List<Dec> RESULT =null;
		Location dxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-1)).xleft;
		Location dxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-1)).xright;
		Dec d = (Dec)((java_cup.runtime.Symbol) CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-1)).value;
		Location dsxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xleft;
		Location dsxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$PandaCup$stack.peek()).xright;
		List<Dec> ds = (List<Dec>)((java_cup.runtime.Symbol) CUP$PandaCup$stack.peek()).value;
		//@@CUPDBG16
 RESULT = ds.prepend(d); 
              CUP$PandaCup$result = parser.getSymbolFactory().newSymbol("decs",4, ((java_cup.runtime.Symbol)CUP$PandaCup$stack.elementAt(CUP$PandaCup$top-1)), ((java_cup.runtime.Symbol)CUP$PandaCup$stack.peek()), RESULT);
            }
          return CUP$PandaCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$PandaCup$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$PandaCup$do_action(
    int                        CUP$PandaCup$act_num,
    java_cup.runtime.lr_parser CUP$PandaCup$parser,
    java.util.Stack            CUP$PandaCup$stack,
    int                        CUP$PandaCup$top)
    throws java.lang.Exception
    {
              return CUP$PandaCup$do_action_part00000000(
                               CUP$PandaCup$act_num,
                               CUP$PandaCup$parser,
                               CUP$PandaCup$stack,
                               CUP$PandaCup$top);
    }
}

}
