
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package panda.Parse;

/** CUP generated interface containing symbol constants. */
public interface PandaSym {
  /* terminals */
  public static final int TIMES = 14;
  public static final int LITBOOL = 3;
  public static final int LITREAL = 8;
  public static final int ELSE = 7;
  public static final int PLUS = 12;
  public static final int RBRACE = 19;
  public static final int RPAREN = 16;
  public static final int THEN = 6;
  public static final int IN = 25;
  public static final int SEMI = 20;
  public static final int WHILE = 10;
  public static final int IF = 5;
  public static final int COLON = 23;
  public static final int LBRACE = 18;
  public static final int LPAREN = 15;
  public static final int ID = 4;
  public static final int LITCHAR = 9;
  public static final int DO = 11;
  public static final int COMMA = 17;
  public static final int EOF = 0;
  public static final int BREAK = 26;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int LET = 24;
  public static final int EQ = 27;
  public static final int ASSIGN = 22;
  public static final int LITINT = 2;
  public static final int VAR = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LITINT",
  "LITBOOL",
  "ID",
  "IF",
  "THEN",
  "ELSE",
  "LITREAL",
  "LITCHAR",
  "WHILE",
  "DO",
  "PLUS",
  "MINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "VAR",
  "ASSIGN",
  "COLON",
  "LET",
  "IN",
  "BREAK",
  "EQ"
  };
}

