
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package panda.Parse;

/** CUP generated interface containing symbol constants. */
public interface PandaSym {
  /* terminals */
  public static final int LITINT = 2;
  public static final int ELSE = 6;
  public static final int THEN = 5;
  public static final int error = 1;
  public static final int LITBOOL = 3;
  public static final int IF = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LITINT",
  "LITBOOL",
  "IF",
  "THEN",
  "ELSE"
  };
}

