
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package panda.Parse;

/** CUP generated interface containing symbol constants. */
public interface PandaSym {
  /* terminals */
  public static final int LITBOOL = 3;
  public static final int LITREAL = 7;
  public static final int ELSE = 6;
  public static final int PLUS = 11;
  public static final int RBRACE = 16;
  public static final int RPAREN = 13;
  public static final int THEN = 5;
  public static final int IN = 22;
  public static final int SEMI = 17;
  public static final int WHILE = 9;
  public static final int IF = 4;
  public static final int COLON = 20;
  public static final int LPAREN = 12;
  public static final int LBRACE = 15;
  public static final int LITCHAR = 8;
  public static final int DO = 10;
  public static final int COMMA = 14;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int LET = 21;
  public static final int ASSIGN = 19;
  public static final int LITINT = 2;
  public static final int VAR = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LITINT",
  "LITBOOL",
  "IF",
  "THEN",
  "ELSE",
  "LITREAL",
  "LITCHAR",
  "WHILE",
  "DO",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "VAR",
  "ASSIGN",
  "COLON",
  "LET",
  "IN"
  };
}

