
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20151001
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class PandaSym {
  /* terminals */
  public static final int POW = 37;
  public static final int FUNCTION = 22;
  public static final int GE = 43;
  public static final int UMINUS = 31;
  public static final int LITSTRING = 6;
  public static final int LPAREN = 9;
  public static final int SEMI = 16;
  public static final int LITBOOL = 4;
  public static final int MINUS = 33;
  public static final int RPAREN = 10;
  public static final int AND = 44;
  public static final int LT = 40;
  public static final int TYPE = 20;
  public static final int NIL = 8;
  public static final int OR = 45;
  public static final int IN = 30;
  public static final int COMMA = 15;
  public static final int DIV = 35;
  public static final int PLUS = 32;
  public static final int ASSIGN = 46;
  public static final int IF = 23;
  public static final int DOT = 18;
  public static final int ID = 7;
  public static final int LE = 41;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int LITREAL = 3;
  public static final int MOD = 36;
  public static final int BREAK = 28;
  public static final int EQ = 38;
  public static final int LBRACK = 13;
  public static final int TIMES = 34;
  public static final int COLON = 17;
  public static final int LBRACE = 11;
  public static final int ELSE = 25;
  public static final int RBRACK = 14;
  public static final int WHILE = 26;
  public static final int LET = 29;
  public static final int THEN = 24;
  public static final int RBRACE = 12;
  public static final int NE = 39;
  public static final int AT = 19;
  public static final int GT = 42;
  public static final int LITINT = 2;
  public static final int VAR = 21;
  public static final int LITCHAR = 5;
  public static final int DO = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LITINT",
  "LITREAL",
  "LITBOOL",
  "LITCHAR",
  "LITSTRING",
  "ID",
  "NIL",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "COMMA",
  "SEMI",
  "COLON",
  "DOT",
  "AT",
  "TYPE",
  "VAR",
  "FUNCTION",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "BREAK",
  "LET",
  "IN",
  "UMINUS",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "POW",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "AND",
  "OR",
  "ASSIGN"
  };
}

